/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBConnection;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
/**
 *
 * @author Hasan
 */
public class Dashboard extends javax.swing.JFrame {
    
    /**
     * Creates new form Dashboard
     */
    
    DBConnection dc;
   
    public Dashboard(DBConnection dc) {
        initComponents();
        this.dc = dc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPane = new javax.swing.JPanel();
        prodBtn = new javax.swing.JLabel();
        emBtn = new javax.swing.JLabel();
        sellBtn = new javax.swing.JLabel();
        supBtn = new javax.swing.JLabel();
        tabPane = new javax.swing.JPanel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setIconImage(new ImageIcon(getClass().getResource("/gui/img/dash.png")).getImage());
        setMinimumSize(new java.awt.Dimension(899, 575));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(106, 137, 204));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jonson Brothers LTD.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 110);

        btnPane.setLayout(null);

        prodBtn.setBackground(new java.awt.Color(44, 44, 84));
        prodBtn.setFont(new java.awt.Font("Orena", 0, 36)); // NOI18N
        prodBtn.setForeground(new java.awt.Color(241, 242, 246));
        prodBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prodBtn.setText("Proucts");
        prodBtn.setOpaque(true);
        prodBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prodBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prodBtnMouseExited(evt);
            }
        });
        btnPane.add(prodBtn);
        prodBtn.setBounds(460, 30, 420, 180);

        emBtn.setBackground(new java.awt.Color(44, 44, 84));
        emBtn.setFont(new java.awt.Font("Orena", 0, 36)); // NOI18N
        emBtn.setForeground(new java.awt.Color(241, 242, 246));
        emBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emBtn.setText("Employee");
        emBtn.setOpaque(true);
        emBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emBtnMouseExited(evt);
            }
        });
        btnPane.add(emBtn);
        emBtn.setBounds(20, 30, 420, 180);

        sellBtn.setBackground(new java.awt.Color(44, 44, 84));
        sellBtn.setFont(new java.awt.Font("Orena", 0, 36)); // NOI18N
        sellBtn.setForeground(new java.awt.Color(241, 242, 246));
        sellBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sellBtn.setText("Sell");
        sellBtn.setOpaque(true);
        sellBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sellBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sellBtnMouseExited(evt);
            }
        });
        btnPane.add(sellBtn);
        sellBtn.setBounds(20, 230, 420, 180);

        supBtn.setBackground(new java.awt.Color(44, 44, 84));
        supBtn.setFont(new java.awt.Font("Orena", 0, 36)); // NOI18N
        supBtn.setForeground(new java.awt.Color(241, 242, 246));
        supBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supBtn.setText("Supply");
        supBtn.setOpaque(true);
        supBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supBtnMouseExited(evt);
            }
        });
        btnPane.add(supBtn);
        supBtn.setBounds(460, 230, 420, 180);

        getContentPane().add(btnPane);
        btnPane.setBounds(0, 110, 900, 440);

        tabPane.setVisible(false);
        tabPane.setMinimumSize(new java.awt.Dimension(899, 575));
        tabPane.setLayout(null);

        back.setBackground(new java.awt.Color(32, 191, 107));
        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/b1.png"))); // NOI18N
        back.setToolTipText("");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        tabPane.add(back);
        back.setBounds(4, 120, 70, 70);

        getContentPane().add(tabPane);
        tabPane.setBounds(0, 0, 899, 575);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emBtnMouseEntered
        // TODO add your handling code here:
        hoverEffect(emBtn);
    }//GEN-LAST:event_emBtnMouseEntered

    private void emBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emBtnMouseExited
        // TODO add your handling code here:
        hoverEffectGone(emBtn);
    }//GEN-LAST:event_emBtnMouseExited

    private void prodBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodBtnMouseEntered
        // TODO add your handling code here:
        hoverEffect(prodBtn);
    }//GEN-LAST:event_prodBtnMouseEntered

    private void prodBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodBtnMouseExited
        // TODO add your handling code here:
        hoverEffectGone(prodBtn);
    }//GEN-LAST:event_prodBtnMouseExited

    private void sellBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBtnMouseEntered
        // TODO add your handling code here:
        hoverEffect(sellBtn);
    }//GEN-LAST:event_sellBtnMouseEntered

    private void sellBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBtnMouseExited
        // TODO add your handling code here:
        hoverEffectGone(sellBtn);
    }//GEN-LAST:event_sellBtnMouseExited

    private void supBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supBtnMouseEntered
        // TODO add your handling code here:
        hoverEffect(supBtn);
    }//GEN-LAST:event_supBtnMouseEntered

    private void supBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supBtnMouseExited
        // TODO add your handling code here:
        hoverEffectGone(supBtn);
    }//GEN-LAST:event_supBtnMouseExited

    private void emBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emBtnMouseClicked

        // TODO add your handling code here:
        String sql = "SELECT * FROM employee";
        ResultSet rs = dc.getRS(sql);
        makeTable(rs);

    }//GEN-LAST:event_emBtnMouseClicked

    private void prodBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodBtnMouseClicked
        // TODO add your handling code here:
        String sql = "SELECT * FROM products";
        ResultSet rs = dc.getRS(sql);
        makeTable(rs);
    }//GEN-LAST:event_prodBtnMouseClicked

    private void sellBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBtnMouseClicked
        // TODO add your handling code here:
        String sql = "SELECT * FROM sell";
        ResultSet rs = dc.getRS(sql);
        makeTable(rs);
    }//GEN-LAST:event_sellBtnMouseClicked

    private void supBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supBtnMouseClicked
        // TODO add your handling code here:
        String sql = "SELECT * FROM supply";
        ResultSet rs = dc.getRS(sql);
        makeTable(rs);
    }//GEN-LAST:event_supBtnMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/b2.png")));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/b1.png")));
    }//GEN-LAST:event_backMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        new Dashboard(this.dc).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBConnection();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel btnPane;
    private javax.swing.JLabel emBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel prodBtn;
    private javax.swing.JLabel sellBtn;
    private javax.swing.JLabel supBtn;
    private javax.swing.JPanel tabPane;
    // End of variables declaration//GEN-END:variables

    private void hoverEffect(JLabel l) {
        l.setBackground(new Color(64, 64, 122)); //rgb(64, 64, 122)
        
    }

    private void hoverEffectGone(JLabel l) {
        l.setBackground(new Color(44,44,84));
    }
    
    

    
    String[][] getDataFromRs(ResultSet rs) throws SQLException{
        ResultSetMetaData rsmd = rs.getMetaData();
        int col = rsmd.getColumnCount();
        int row = (rs.last()?rs.getRow():0);
        System.out.println(row);
        String[][] data = new String[row][col];
        rs.beforeFirst();
        int r = 0, c;
        while(rs.next()){
            for(c = 1; c<=col; c++){
                data[r][c-1] = rs.getString(c);
                System.out.println(data[r][c-1]);
            }
            r++;

        }
        return data;
    }

    private String[] getCoLbl(ResultSet rs) throws SQLException {
        ResultSetMetaData rsmd = rs.getMetaData();
        int col = rsmd.getColumnCount();
        String colum[] = new String[col];
        for(int i = 1; i <= col; i++){
            colum[i-1] = rsmd.getColumnLabel(i);
        }
        
        return colum;
    }

    private void makeTable(ResultSet rs) {
        try {
            String data[][] = this.getDataFromRs(rs);
            String column[] = getCoLbl(rs) ;
            System.out.println("make");
            this.btnPane.setVisible(false);
            JTable table = new JTable(data,column);
            table.setEnabled(false);
            JScrollPane sp = new JScrollPane(table);
            sp.setBounds(110, 130, 700 , 400);
            tabPane.add(sp);
            this.tabPane.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
}
